repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723
    hooks:
      - id: prettier
        args: ['--plugin=@prettier/plugin-php']
        additional_dependencies: ['@prettier/plugin-php@0.17.6']
  - repo: https://github.com/apeschar/phan
    rev: e56968f2b00d19c3c8d3ee113b9d7255eca7cccd
    hooks:
      - id: phan
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: b762b86f28cb684ac10287ecb0e4420d5c320ab3
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 534492d910ad4a4d484470b5aa0d51f1274eab1e
    hooks:
      - id: eslint
