repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723
    hooks:
      - id: prettier
        args: ['--plugin=@prettier/plugin-php']
        additional_dependencies: ['@prettier/plugin-php@0.17.6']
  - repo: https://github.com/apeschar/phan
    rev: e56968f2b00d19c3c8d3ee113b9d7255eca7cccd
    hooks:
      - id: phan
