version: '3.9'

services:
  php:
    build: docker/php
    environment:
      DATABASE_URL: mysql://root@mariadb/shopware
      APP_URL: http://localhost:26740
      APP_SECRET: shopware
      COMPOSER_HOME: /data/shopware/var/cache/composer
      PRICEMOTION_CLOUDFLARED_METRICS_URL: http://cloudflared:8080
    volumes:
      - .:/data
      - ./docker/php/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-local.ini
    ports:
      - 26740:80

  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: shopware
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 26741:3306
    healthcheck:
      test: ['CMD', 'mysql', '-e', '', 'shopware']
      interval: 1s
      start_period: 30s

  cloudflared:
    image: cloudflare/cloudflared:1299-cf87ec796995
    command: tunnel --url http://php --http-host-header localhost:26740 --metrics 0.0.0.0:8080
    ports:
      - 26742:8080

volumes:
  mariadb:
